FROM golang:1.21-alpine AS builder

WORKDIR /src
COPY . .
RUN go mod download && go mod tidy
RUN go build -o ./app ./main.go

FROM alpine:latest AS runner
WORKDIR /src
COPY --from=builder /src/app /src/app
EXPOSE 8080
ENTRYPOINT ["/src/app"]